# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Games-AlphaBeta
version:      0.11
version_from: lib/Games/AlphaBeta.pm
installdirs:  site
requires:
    Games::Sequential:             0.11

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
