---
name: Games-AlphaBeta
version: 0.4.6
author:
  - 'Stig Brautaset, E<lt>stig@brautaset.orgE<gt>'
abstract: game-tree search with object oriented interface
license: perl
build_requires:
  File::Spec::Functions: 0
  Test::More: 0
provides:
  Games::AlphaBeta:
    file: lib/Games/AlphaBeta.pm
    version: 0.4.6
  Games::AlphaBeta::Position:
    file: lib/Games/AlphaBeta/Position.pm
    version: 0.1.2
  Games::AlphaBeta::Reversi:
    file: lib/Games/AlphaBeta/Reversi.pm
    version: 0.1.5
  Games::Sequential:
    file: lib/Games/Sequential.pm
    version: 0.4.2
  Games::Sequential::Position:
    file: lib/Games/Sequential/Position.pm
    version: 0.3.1
generated_by: Module::Build version 0.2611
